
package documentservices.wms0.rbcfg.servicemessage;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-02-16T10:44:40.002+05:30
 * Generated source version: 2.7.8
 * 
 */
public final class WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage_CustomBindingITwoWayAsync_Client {

    private static final QName SERVICE_NAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage/", "BizTalkServiceInstance");

    private WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage_CustomBindingITwoWayAsync_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BizTalkServiceInstance.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BizTalkServiceInstance ss = new BizTalkServiceInstance(wsdlURL, SERVICE_NAME);
        WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage port = ss.getCustomBindingITwoWayAsync();  
        
        {
        System.out.println("Invoking opRcvSndDSMessage...");
        documentservices.wms0.rbcfg.servicemessage.DocumentServices _opRcvSndDSMessage_partVal = new documentservices.wms0.rbcfg.servicemessage.DocumentServices();
        documentservices.wms0.rbcfg.servicemessage.UserAuthRequest _opRcvSndDSMessage_partValUserAuthRequest = new documentservices.wms0.rbcfg.servicemessage.UserAuthRequest();
        _opRcvSndDSMessage_partValUserAuthRequest.setUserID("UserID-745484888");
        _opRcvSndDSMessage_partValUserAuthRequest.setUserRole("UserRole-396982490");
        documentservices.wms0.rbcfg.servicemessage.Application _opRcvSndDSMessage_partValUserAuthRequestApplication = new documentservices.wms0.rbcfg.servicemessage.Application();
        _opRcvSndDSMessage_partValUserAuthRequestApplication.setApplicationCode("ApplicationCode724832329");
        _opRcvSndDSMessage_partValUserAuthRequestApplication.setLanguageCode("LanguageCode155330941");
        _opRcvSndDSMessage_partValUserAuthRequest.setApplication(_opRcvSndDSMessage_partValUserAuthRequestApplication);
        _opRcvSndDSMessage_partVal.setUserAuthRequest(_opRcvSndDSMessage_partValUserAuthRequest);
        documentservices.wms0.rbcfg.servicemessage.DocumentServiceRequest _opRcvSndDSMessage_partValDocumentServiceRequest = new documentservices.wms0.rbcfg.servicemessage.DocumentServiceRequest();
        _opRcvSndDSMessage_partValDocumentServiceRequest.setTransactionGUID("TransactionGUID1052547273");
        _opRcvSndDSMessage_partValDocumentServiceRequest.setTransactionType("TransactionType-635639118");
        _opRcvSndDSMessage_partValDocumentServiceRequest.setTransactionDescription("TransactionDescription-205343109");
        _opRcvSndDSMessage_partValDocumentServiceRequest.setTransactionDate("TransactionDate248732260");
        _opRcvSndDSMessage_partValDocumentServiceRequest.setTransactionTime("TransactionTime679833698");
        _opRcvSndDSMessage_partValDocumentServiceRequest.setIncludeDocumentImage(Boolean.valueOf(false));
        documentservices.wms0.rbcfg.servicemessage.MetaDataFields _opRcvSndDSMessage_partValDocumentServiceRequestMetaDataFields = new documentservices.wms0.rbcfg.servicemessage.MetaDataFields();
        java.util.List<documentservices.wms0.rbcfg.servicemessage.MetaDataField> _opRcvSndDSMessage_partValDocumentServiceRequestMetaDataFieldsMetaDataField = new java.util.ArrayList<documentservices.wms0.rbcfg.servicemessage.MetaDataField>();
        _opRcvSndDSMessage_partValDocumentServiceRequestMetaDataFields.getMetaDataField().addAll(_opRcvSndDSMessage_partValDocumentServiceRequestMetaDataFieldsMetaDataField);
        _opRcvSndDSMessage_partValDocumentServiceRequest.setMetaDataFields(_opRcvSndDSMessage_partValDocumentServiceRequestMetaDataFields);
        documentservices.wms0.rbcfg.servicemessage.Content _opRcvSndDSMessage_partValDocumentServiceRequestContent = new documentservices.wms0.rbcfg.servicemessage.Content();
        _opRcvSndDSMessage_partValDocumentServiceRequestContent.setObjectMimeType("ObjectMimeType-586326080");
        javax.activation.DataHandler _opRcvSndDSMessage_partValDocumentServiceRequestContentObjectContent = null;
        _opRcvSndDSMessage_partValDocumentServiceRequestContent.setObjectContent(_opRcvSndDSMessage_partValDocumentServiceRequestContentObjectContent);
        _opRcvSndDSMessage_partValDocumentServiceRequest.setContent(_opRcvSndDSMessage_partValDocumentServiceRequestContent);
        documentservices.wms0.rbcfg.servicemessage.Packages _opRcvSndDSMessage_partValDocumentServiceRequestPackages = new documentservices.wms0.rbcfg.servicemessage.Packages();
        java.util.List<documentservices.wms0.rbcfg.servicemessage.Package> _opRcvSndDSMessage_partValDocumentServiceRequestPackagesPackage = new java.util.ArrayList<documentservices.wms0.rbcfg.servicemessage.Package>();
        _opRcvSndDSMessage_partValDocumentServiceRequestPackages.getPackage().addAll(_opRcvSndDSMessage_partValDocumentServiceRequestPackagesPackage);
        _opRcvSndDSMessage_partValDocumentServiceRequest.setPackages(_opRcvSndDSMessage_partValDocumentServiceRequestPackages);
        _opRcvSndDSMessage_partVal.setDocumentServiceRequest(_opRcvSndDSMessage_partValDocumentServiceRequest);
        documentservices.wms0.rbcfg.servicemessage.UserAuthResponse _opRcvSndDSMessage_partValUserAuthResponse = new documentservices.wms0.rbcfg.servicemessage.UserAuthResponse();
        documentservices.wms0.rbcfg.servicemessage.TransactionResult _opRcvSndDSMessage_partValUserAuthResponseTransactionResult = new documentservices.wms0.rbcfg.servicemessage.TransactionResult();
        _opRcvSndDSMessage_partValUserAuthResponseTransactionResult.setResultCode(1924547610);
        _opRcvSndDSMessage_partValUserAuthResponseTransactionResult.setResultDescription("ResultDescription-1439809700");
        _opRcvSndDSMessage_partValUserAuthResponse.setTransactionResult(_opRcvSndDSMessage_partValUserAuthResponseTransactionResult);
        _opRcvSndDSMessage_partVal.setUserAuthResponse(_opRcvSndDSMessage_partValUserAuthResponse);
        documentservices.wms0.rbcfg.servicemessage.DocumentServiceResponse _opRcvSndDSMessage_partValDocumentServiceResponse = new documentservices.wms0.rbcfg.servicemessage.DocumentServiceResponse();
        _opRcvSndDSMessage_partValDocumentServiceResponse.setTransactionGUID("TransactionGUID-183709377");
        documentservices.wms0.rbcfg.servicemessage.TransactionResult _opRcvSndDSMessage_partValDocumentServiceResponseTransactionResult = new documentservices.wms0.rbcfg.servicemessage.TransactionResult();
        _opRcvSndDSMessage_partValDocumentServiceResponseTransactionResult.setResultCode(-1647377311);
        _opRcvSndDSMessage_partValDocumentServiceResponseTransactionResult.setResultDescription("ResultDescription-1260895617");
        _opRcvSndDSMessage_partValDocumentServiceResponse.setTransactionResult(_opRcvSndDSMessage_partValDocumentServiceResponseTransactionResult);
        _opRcvSndDSMessage_partValDocumentServiceResponse.setIncludeDocumentImage(Boolean.valueOf(true));
        documentservices.wms0.rbcfg.servicemessage.Documents _opRcvSndDSMessage_partValDocumentServiceResponseDocuments = new documentservices.wms0.rbcfg.servicemessage.Documents();
        java.util.List<documentservices.wms0.rbcfg.servicemessage.Document> _opRcvSndDSMessage_partValDocumentServiceResponseDocumentsDocument = new java.util.ArrayList<documentservices.wms0.rbcfg.servicemessage.Document>();
        _opRcvSndDSMessage_partValDocumentServiceResponseDocuments.getDocument().addAll(_opRcvSndDSMessage_partValDocumentServiceResponseDocumentsDocument);
        _opRcvSndDSMessage_partValDocumentServiceResponse.setDocuments(_opRcvSndDSMessage_partValDocumentServiceResponseDocuments);
        _opRcvSndDSMessage_partVal.setDocumentServiceResponse(_opRcvSndDSMessage_partValDocumentServiceResponse);
        _opRcvSndDSMessage_partVal.setVersion("Version-990647169");
        javax.xml.ws.Holder<documentservices.wms0.rbcfg.servicemessage.DocumentServices> _opRcvSndDSMessage_part = new javax.xml.ws.Holder<documentservices.wms0.rbcfg.servicemessage.DocumentServices>(_opRcvSndDSMessage_partVal);
        port.opRcvSndDSMessage(_opRcvSndDSMessage_part);

        System.out.println("opRcvSndDSMessage._opRcvSndDSMessage_part=" + _opRcvSndDSMessage_part.value);

        }

        System.exit(0);
    }

}
