
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package documentservices.wms0.rbcfg.servicemessage;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-02-16T10:44:40.065+05:30
 * Generated source version: 2.7.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "BizTalkServiceInstance",
                      portName = "CustomBinding_ITwoWayAsync",
                      targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage/",
                      wsdlLocation = "http://localhost:7999/WS_CXF_Service/services/CustomBinding_ITwoWayAsync?wsdl",
                      endpointInterface = "documentservices.wms0.rbcfg.servicemessage.WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage")
                      
public class WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessageImpl implements WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage {

    private static final Logger LOG = Logger.getLogger(WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessageImpl.class.getName());

    /* (non-Javadoc)
     * @see documentservices.wms0.rbcfg.servicemessage.WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage#opRcvSndDSMessage(documentservices.wms0.rbcfg.servicemessage.DocumentServices  part )*
     */
    public void opRcvSndDSMessage(javax.xml.ws.Holder<DocumentServices> part) { 
        LOG.info("Executing operation opRcvSndDSMessage");
        System.out.println(part.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
