package documentservices.wms0.rbcfg.servicemessage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-02-16T10:44:40.080+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage/", name = "WMS0_DS_WebService_BT_Orc_Core_ProcessDocumentService_PortRcvSndDSMessage")
@XmlSeeAlso({com.microsoft.schemas.message.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage {

    /**
     * operation &quot;OpRcvSndDSMessage&quot;
     */
    @Action(input = "OpRcvSndDSMessage", output = "http://RBCFG.WMS0.DocumentServices/ServiceMessage/WMS0_DS_WebService_BT_Orc_Core_ProcessDocumentService_PortRcvSndDSMessage/OpRcvSndDSMessageResponse")
    @WebMethod(operationName = "OpRcvSndDSMessage", action = "OpRcvSndDSMessage")
    public void opRcvSndDSMessage(
        @WebParam(partName = "part", mode = WebParam.Mode.INOUT, name = "DocumentServices", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage")
        javax.xml.ws.Holder<DocumentServices> part
    );
}
